name: streambox_core
description: Core for stream-based caching and data strategy architecture.
version: 1.4.2
homepage: https://github.com/kalaganov/streambox_core
issue_tracker: https://github.com/kalaganov/streambox_core/issues
topics:
  - repository
  - caching
  - reactive
  - strategy
  - core

environment:
  sdk: ^3.8.1

dependencies:
  meta: ^1.16.0 # https://pub.dev/packages/meta

dev_dependencies:
  async: ^2.13.0
  test: ^1.26.2 # https://pub.dev/packages/test
  very_good_analysis: ^9.0.0 # https://pub.dev/packages/very_good_analysis
